<?php

return array(
    __('Outright Winner'),
    __('Match Result'),
    __('Double Chance'),
    __('Correct Score'),
    __('Half-Time Result'),
    __('Half-Time / Full-Time'),
    __('First Team To Score'),
    __('Total Goals'),
    __('Under/Over'),
    __('Handicap'),
    __('First Goalscorer'),
    __('Last Goalscorer'),
    __('Goalscorer'),
    __('Place 1-4'),
    __('Relegation'),
    __('Place 1-3'),
    __('Number of Goals'),
    __('Half-Time Correct Score'),
    __('Match Winner'),
    __('Drivers Championship Winner'),
    __('Constructors Championship'),
    __('Winner'),
    __('Total Points'),
    __('Handicap Result'),
    __('Match Result 2'),
    __('Stage Winner'),
    __('First Set Total Points'),
    __('Sets Handicap'),
    __('Total Sets'),
    __('Match Winner 2'),
    __('Total Goals Odd/Even'),
    __('First Period Result'),
    __('Second Period Result'),
    __('Third Period Result'),
    __('First Period Total Goals'),
    __('Second Period Total Goals'),
    __('Third Period Total Goals'),
    __('Time of First Goal'),
    __('First Period Double Chance'),
    __('Second Period Double Chance'),
    __('Third Period Double Chance'),
    __('Race to 3 Goals'),
    __('Away Team Total Goals'),
    __('Home Team Total Goals'),
    __('Drivers Winner'),
    __('Championship Winner'),
    __('Head-to-Head Race'),
    __('Total Goals Line'),
    __('Clean Sheet'),
    __('Half with Most Goals'),
    __('Match Result/Both Teams to Score'),
    __('First Half Result/Both Teams to Score'),
    __('Home Team to Win to Nil'),
    __('Away Team to Win to Nil'),
    __('1st Half Goals Odd/Even'),
    __('Away Team Over/Under'),
    __('Home Team Over/Under'),
    __('Away Team 1st Half Clean Sheet'),
    __('Home Team 1st Half Clean Sheet'),
    __('Double Chance & Both Teams to Score'),
    __('1st Half Handicap'),
    __('1st Half Over/Under'),
    __('1st Half Total Goals'),
    __('Draw no Bet'),
    __('Home Team 1st Half Over/Under'),
    __('Half Time Both Teams To Score'),
    __('Away Team Total Goals Odd/Even'),
    __('Half Time Draw No Bet'),
    __('Next Goal in the 1st Half'),
    __('Home Team Total Goals Odd/Even'),
    __('Next Goal in regular time '),
    __('Both Teams to Score'),
    __('Home Team Clean Sheet'),
    __('Away Team Clean Sheet'),
    __('Away Team 1st Half Over/Under'),
    __('Half Time Double Chance'),
    __('Match and Goals'),
    __('Next Away Goal Time'),
    __('Next Goal Time'),
    __('Next Home Goal Time'),
    __('Player to score 3 or more'),
    __('Player to Score 2 or more'),
    __('Next Goalscorer'),
    __('Over/Under After 85 Minutes'),
    __('Over/Under After 80 Minutes'),
    __('Over/Under After 75 Minutes'),
    __('Over/Under After 70 Minutes'),
    __('Over/Under After 65 Minutes'),
    __('Over/Under After 60 Minutes'),
    __('Over/Under After 55 Minutes'),
    __('Over/Under After 50 Minutes'),
    __('Over/Under After 45 Minutes'),
    __('Over/Under After 40 Minutes'),
    __('Over/Under After 35 Minutes'),
    __('Over/Under After 30 Minutes'),
    __('Over/Under After 25 Minutes'),
    __('Over/Under After 20 Minutes'),
    __('Game Handicap'),
    __('Total Games'),
    __('Series Winner'),
    __('Regular Season Winner'),
    __('First Round 2 Ball'),
    __('Tournament Match Bet'),
    __('Total Runs'),
    __('Champion'),
    __('Second Set Winner'),
    __('First Set Winner'),
    __('Winning Team'),
    __('Podium'),
    __('Points Classification'),
    __('Conference Winner'),
    __('Test Set Winner'),
    __('Test2 Set Winner'),
    __('Tie Winner'),
    __('Half Time Result'),
    __('Half Time / Full Time'),
    __('Top European'),
    __('Top American'),
    __('Third Set Winner'),
    __('Tie Outcome'),
    __('Fourth Set Winner')
);