var CANVAS_WIDTH = 750;
var CANVAS_HEIGHT = 600;

var FPS_TIME      = 1000/24;
var DISABLE_SOUND_MOBILE = false;

var STATE_LOADING = 0;
var STATE_MENU    = 1;
var STATE_HELP    = 1;
var STATE_GAME    = 3;

var STATE_GAME_WAITING_FOR_BET = 0;
var STATE_GAME_SPINNING        = 1;
var STATE_GAME_SHOW_WINNER     = 2;
var STATE_DISTRIBUTE_FICHES    = 3;

var ON_SHOW_BET_ON_TABLE = 0;
var ON_SHOW_ENLIGHT = 1;
var ON_HIDE_ENLIGHT = 2;

var ON_MOUSE_DOWN = 0;
var ON_MOUSE_UP   = 1;
var ON_MOUSE_OVER = 2;
var ON_MOUSE_OUT  = 3;
var ON_DRAG_START = 4;
var ON_DRAG_END   = 5;

var COLOR_RED   = "red";
var COLOR_BLACK = "black";
var COLOR_ZERO  = "zero";

var TOTAL_MONEY;
var NUM_FICHE_VALUES = 6;
var NUMBERS_TO_BET =37;
var NUM_FICHES = 6;
var MIN_BET;
var MAX_BET;
var WIN_OCCURRENCE;
var TIME_WAITING_BET;
var TIME_SPINNING = 3500;
var TIME_SHOW_WINNER;
var TIME_FICHES_MOV = 500;
var NUM_WHEEL_TOP_FRAMES = 200;
var NUM_MASK_BALL_SPIN_FRAMES = 200;
var NUM_BALL_SPIN_FRAMES = 400;
var NUM_HAND_FOR_ADS;

var FONT1 = "arialbold";
var FONT2 = "Digital-7";
var ENABLE_FULLSCREEN;
var ENABLE_CHECK_ORIENTATION;