TEXT_PRELOADER_CONTINUE = "START GAME";
TEXT_WIN  = "YOU WIN";
TEXT_CONGRATS = "CONGRATULATIONS!";
TEXT_NO_WIN    = "YOU LOST YOUR CREDITS";
TEXT_PLAY      = "PLAY";
TEXT_HELP1     = "SCRATCH THE SILVER SQUARES. IF YOU FIND THREE IDENTICAL SYMBOLS, YOU WIN THE PRIZE!!";
TEXT_ARE_SURE = "ARE YOU SURE?";

TEXT_HEAD       = "WIN TOP PRIZES!";
TEXT_CURRENCY  = "$";
TEXT_ADVICE_WIN = "WIN";
TEXT_ADVICE_LOSE = "NO WIN";

TEXT_CREDIT = "CREDIT";
TEXT_PLUS = "+";
TEXT_MINUS = "-";
TEXT_BUYCARD = "BUY A CARD";
TEXT_WIN_AMOUNT = "WIN AMOUNT";
TEXT_CARD_VALUE = "BET";
TEXT_PLAY_AGAIN = "PLAY AGAIN";

TEXT_SHARE_IMAGE = "200x200.jpg";
TEXT_SHARE_TITLE = "Congratulations!";
TEXT_SHARE_MSG1 = "You collected <strong>";
TEXT_SHARE_MSG2 = " points</strong>!<br><br>Share your score with your friends!";
TEXT_SHARE_SHARE1 = "My score is ";
TEXT_SHARE_SHARE2 = " points! Can you do better?";