TEXT_GAMEOVER  = "YOUR BALANCE IS 0!\nDEPOSIT FUNDS TO PLAY";
TEXT_ALLIN     = "ALL IN!";
TEXT_CLEARBET  = "CLEAR BET";
TEXT_GIVEUP    = "GIVE UP";
TEXT_MAKE      = "MAKE YOUR BET!";
TEXT_ENDGIVEUP = "ARE YOU SURE TO EXIT AND SAVE ";
TEXT_YES       = "YES";
TEXT_NO        = "NO";

TEXT_CURRENCY = "$";

TEXT_TURN = "TURN ";
TEXT_HIGHS = "HIGHs: ";
TEXT_LOWS = "LOWs: ";
TEXT_GUESS = "TOTAL GUESS: ";
TEXT_BEST = "BEST SCORE: ";

TEXT_WIN = "YOU WIN";
TEXT_LOSE = "YOU LOSE";
var TEXT_CREDITS_DEVELOPED = "DEVELOPED BY";

TEXT_HELP1     = "THE AIM OF THE GAME IS TO GUESS WHETHER THE FACE DOWN CARD IS HIGH OR LOW";
TEXT_HELP2     = "CARDS FROM 2 TO 7 ARE LOW THOSE BETWEEN 8 AND KING ARE HIGH. THE ACE IS BOTH HIGH AND LOW, SO IT'S ALWAYS WINNING";
TEXT_HELP3     = 'CLICK ON CHIPS TO CHOOSE HOW MUCH YOU WANT BET, THEN CLICK ON "BET" BUTTON TO PLAY. IF YOU WIN, YOU DOUBLE YOUR WAGER';
TEXT_HELP4     = 'TO SAVE YOUR CURRENT PRIZE MONEY, CLICK ON "GIVE UP" BUTTON, THIS WILL END YOUR GAME';

TEXT_SHARE_IMAGE = "200x200.jpg";
TEXT_SHARE_TITLE = "Congratulations!";
TEXT_SHARE_MSG1 = "You collected <strong>";
TEXT_SHARE_MSG2 = " points</strong>!<br><br>Share your score with your friends!";
TEXT_SHARE_SHARE1 = "My score is ";
TEXT_SHARE_SHARE2 = " points! Can you do better";