var CANVAS_WIDTH = 1600;
var CANVAS_HEIGHT = 768;

var EDGEBOARD_X = 240;
var EDGEBOARD_Y = 0;

var FPS_TIME      = 1000/24;
var DISABLE_SOUND_MOBILE = false;

var PRIMARY_FONT = "arialbold";

var STATE_LOADING = 0;
var STATE_MENU    = 1;
var STATE_HELP    = 1;
var STATE_GAME    = 3;

var ON_MOUSE_DOWN  = 0;
var ON_MOUSE_UP    = 1;
var ON_MOUSE_OVER  = 2;
var ON_MOUSE_OUT   = 3;
var ON_DRAG_START  = 4;
var ON_DRAG_END    = 5;

var FICHE_WIDTH = 40;
var FICHE_VALUE = new Array();

var WIN_OCCURRENCE;

var TURN_CARD_SPEED;
var CARD_WIDTH = 122;
var CARD_HEIGHT = 190;

var SHOWTEXT_SPEED;

var START_MONEY;
var GAME_CASH;

var AD_SHOW_COUNTER;
var ENABLE_FULLSCREEN;
var ENABLE_CHECK_ORIENTATION;