var TEXT_DEAL      = "DEAL";
var TEXT_MIN_BET   = "MIN BET";
var TEXT_MAX_BET   = "MAX BET";
var TEXT_RECHARGE  = "RECHARGE";
var TEXT_EXIT      = "EXIT";
var TEXT_MONEY     = "MONEY";
var TEXT_CURRENCY  = "$";
var TEXT_RAISE     = "RAISE";
var TEXT_FOLD      = "FOLD";
var TEXT_CREDITS_DEVELOPED = "DEVELOPED BY";

var TEXT_DISPLAY_MSG_WAITING_BET = "WAITING FOR YOUR BET";
var TEXT_DISPLAY_MSG_PLAYER_LOSE = "PLAYER LOSES THIS HAND!";
var TEXT_DISPLAY_MSG_STANDOFF = "STAND OFF";
var TEXT_DISPLAY_MSG_PLAYER_WIN = "PLAYER WINS";
var TEXT_DISPLAY_MSG_USER_TURN = "PLAYER TURN. RAISE OR FOLD?";
var TEXT_DISPLAY_MSG_SHOWDOWN = "SHOWDOWN!";
var TEXT_DISPLAY_MSG_DEALING = "DEALING...";
var TEXT_DISPLAY_MSG_NOT_QUALIFY = "DEALER DOES NOT QUALIFY";
var TEXT_NO_MONEY = "YOU DON'T HAVE ENOUGH MONEY!!!";
var TEXT_NO_MONEY_FOR_RAISE = "YOU DON'T HAVE ENOUGH MONEY FOR RAISE BET EVENTUALLY!!!";
var TEXT_HAND_WON_PLAYER = "HAND WON BY THE PLAYER";
var TEXT_HAND_WON_DEALER = "HAND WON BY THE DEALER";
var TEXT_ERROR_MIN_BET = "YOUR BET IS LOWER THAN MINIMUM BET!!";
var TEXT_ERROR_MAX_BET = "YOUR BET IS HIGHER THAN MAXIMUM BET!!";


var TEXT_EVALUATOR = new Array();
TEXT_EVALUATOR[0] = "ROYAL FLUSH";
TEXT_EVALUATOR[1] = "STRAIGHT FLUSH";
TEXT_EVALUATOR[2] = "FOUR OF A KIND";
TEXT_EVALUATOR[3] = "FULL HOUSE";
TEXT_EVALUATOR[4] = "FLUSH";
TEXT_EVALUATOR[5] = "STRAIGHT";
TEXT_EVALUATOR[6] = "THREE OF A KIND";
TEXT_EVALUATOR[7] = "TWO PAIR";
TEXT_EVALUATOR[8] = "ONE PAIR";
TEXT_EVALUATOR[9] = "HIGH CARD";
TEXT_EVALUATOR[10] = "NO HAND";
       

var TEXT_SHARE_IMAGE = "200x200.jpg";
var TEXT_SHARE_TITLE = "Congratulations!";
var TEXT_SHARE_MSG1 = "You collected <strong>";
var TEXT_SHARE_MSG2 = " points</strong>!<br><br>Share your score with your friends!";
var TEXT_SHARE_SHARE1 = "My score is ";
var TEXT_SHARE_SHARE2 = " points! Can you do better?";